# Site settings
title: Hive CI | CI for device testing
description: >
  Device-centric CI
sass:
  sass_dir: _sass

baseurl: /hive-ci

# Build settings
markdown: kramdown

collections:
  documentation:
    output: true

navigation:
  - text: Hive CI
    url: /documentation/hive-ci.html
  - text: HiveMind
    url: /hivemind.html
  - text: TestMine
    url: /testmine.html
  - text: Test Tools
    url: /test-tools.html
